name: Deploy EPANET 2.2 docs to GitHub Pages

on:
  push:
    branches: [ master ]          # or main
  pull_request:
    branches: [ master ]

permissions:
  contents: write                 # gh-pages push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCS_DIR: User_Manual/docs  # ← centralised path
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Sphinx + theme
        run: |
          pip install -r $DOCS_DIR/requirements.txt

      - name: Build HTML
        run: |
          sphinx-build -b html $DOCS_DIR $DOCS_DIR/_build/html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4    # rock-solid Pages deployer
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.DOCS_DIR }}/_build/html
