name: Build & Deploy docs to GitHub Pages

on:
  push:
    branches: [ master ]
    paths:
      - 'User_Manual/**'
      - '.github/workflows/pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Sphinx toolchain
        run: |
          python -m pip install --upgrade pip
          # If you have a requirements file, prefer it. Otherwise install a safe baseline:
          if [ -f "User_Manual/docs/requirements.txt" ]; then
            pip install -r User_Manual/docs/requirements.txt
          else
            pip install "sphinx>=7,<8" sphinx-rtd-theme myst-parser
          fi

      - name: Build HTML
        run: |
          # Adjust if your Sphinx source dir differs
          # Typical layouts (pick one that exists):
          for P in \
            User_Manual/docs/source \
            User_Manual/docs \
            User_Manual; do
            if [ -f "$P/conf.py" ]; then SRC="$P"; break; fi
          done
          echo "Using Sphinx source: $SRC"
          sphinx-build -b html "$SRC" site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


